import { DM_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import { Header } from '@/components/header/Header';
import './globals.css';

const dmSans = DM_Sans({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-dm-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable}`} >
        <div className="container">
          <Header/>
          <main>
            {children}
          </main>
          <footer>footer</footer>
        </div>
      </body>
    </html>
  );
}
