import { DM_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import Logo from '@/components/logo/Logo';
import './globals.css';

const dmSans = DM_Sans({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-dm-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable}`} >
        <header>
          <Logo />
        </header>
        <main>
          {children}
        </main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
