import type { Metadata } from 'next';
import { Header } from '@/layouts/header/Header';
import { dmSans } from '@/styles/fonts';
import './globals.css';
import { Footer } from '@/layouts/footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={dmSans.variable}>
      <body>
        <div className='container'>
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
