import type { Metadata } from 'next';
import { Header } from '@/layouts/header/Header';
import { Footer } from '@/layouts/footer/Footer';
import { AuthInitializer } from '@/components/authInitializer/AuthInitializer';
import { PageTransitions } from '@/components/pageTransitons/PageTransitions';
import StoreProvider from './StoreProvider';
import { dmSans } from '@/styles/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={dmSans.variable}>
      <body>
        <div className='container'>
          <StoreProvider>
            <Header />
            <AuthInitializer />
            <main>
              <PageTransitions>
                {children}
              </PageTransitions>
            </main>
            <Footer />
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
