import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Страница входа и авторизации',
  // description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={'auth'}>
        {/* <header></header> */}
        <main className='auth-content'>{children}</main>
        {/* <footer></footer> */}
      </body>
    </html>
  );
}
